### ISSUE TITLE
new style code-generation directives aren't highlighted in file editors like the old style ones

### ISSUE THREAD

**Issue by bikeNomad** [QuantumLeaps/qm#1]
Though the QM docs (for 4.1.0) say that the new-style code generation directives like `$declare${...}` are preferred to the old-style ones like `$declare(...)`, the new directives aren't highlighted in red and underlined like the old ones are:

![image](https://user-images.githubusercontent.com/99482/33445847-061c8e00-d5b3-11e7-8998-e5842b74b3aa.png)

The code generation works the same for both syntaxes, though.

**Comment by quantum-leaps** [comment]
This issue has been fixed in QM 4.1.1. 
See also https://sourceforge.net/p/qpc/bugs/195/ 
--MMS
