### ISSUE TITLE
where is QM source code?

### ISSUE THREAD

**Issue by ponyatov** [QuantumLeaps/qm#13]
I want to make some fixes in QM, so I cloned this repo, and did not find any source inside -- is this the OpenSource project?

**Comment by quantum-leaps** [comment]
QM is freeware, but not open source. Please check the [QM license](https://github.com/QuantumLeaps/qm/blob/main/LICENSE.txt) included in the QM repository.

**Comment by ponyatov** [comment]
And there is no plans to open part of it to let it to be developed and supported by the user's public community?

**Comment by ponyatov** [comment]
custom compiler for .qm files can be enough for most cases
