### ISSUE TITLE
No shortcut feature

### ISSUE THREAD

**Issue by reeraslan** [QuantumLeaps/qm#15]
I searched through all of the provided documents to see if there's an option to assign shortcuts for the editor tools but can't seem to find any. Is there any way to have the ability of shortcuts if not would you be able to consider adding as a new feature for next release?
Thanks

**Comment by quantum-leaps** [comment]
I'm not sure which shortcuts you mean. But QM supports some standard shortcuts, as shown in the attached screen shot.
--MMS
![qm-shortcuts](https://github.com/QuantumLeaps/qm/assets/9914925/10a8ebd2-9476-4fb4-b176-e935f58498e7)

**Comment by reeraslan** [comment]
I meant shortcuts for the model editor elements like selecting Transition or state on the left bar
![image](https://github.com/QuantumLeaps/qm/assets/2240871/74ada512-9729-4c85-8b89-d51e8219b1cd)
