### ISSUE TITLE
QM 5.3.0 on Linux - or is it QM 5.2.5

### ISSUE THREAD

**Issue by teivah-tech** [QuantumLeaps/qm#16]
Running latest qm_5.3.0-linux64.zip:

https://github.com/QuantumLeaps/qm/releases/download/v5.3.0/qm_5.3.0-linux64.zip

- Tool still says 5.2.5 in About QM.
- Can't open the template files with new project; getting ERROR F041.
- Generated code says "This code has been generated by QM 5.2.5".

There seems to be some confusion between version 5.3.0 and 5.2.5 in the latest upload?

**Comment by quantum-leaps** [comment]
Thanks for reporting. The issue has been fixed. Please download [qm_5.3.0-linux64.zip](https://github.com/QuantumLeaps/qm/releases/download/v5.3.0/qm_5.3.0-linux64.zip) again.
--MMS

**Comment by teivah-tech** [comment]
Kudos @quantum-leaps for the lightning fast fix! Thank you!
