### ISSUE TITLE
QM 6.1.0 fails to load legacy model from QM 5.2.5

### ISSUE THREAD

**Issue by smartinou** [QuantumLeaps/qm#19]
I recently moved to QM 6.1.0 Linux, on Ubuntu 22.04LTS.
It failed to load legacy models built with QM 5.2.5. When attempting to do this, I get a pop up error:

![Screenshot from 2024-01-08 20-30-38](https://github.com/QuantumLeaps/qm/assets/40808351/87e04b49-b515-461d-a03c-b9e31a82e9ff)

Luckily, I checked the release notes found here: https://www.state-machine.com/qm/history.html#qm_6_1_0
The note about the new xml element ```external_package``` caught my attention. My model has an external package (.qpm) file. I manually edited the .qm file to replace the tag:
```<package file="./gui.qmp"/>```
with...
```<extern_package file="./gui.qmp"/>```

... and the model successfully loaded.

According to the Note section of the release notes under 6.1.0, this change should have been backward compatible, but it seems like it's not.

Links to gui.qp and gui.qpm files that reproduce the issue: https://github.com/smartinou/pfpp/tree/main/firmware/qp_ao/models

**Comment by quantum-leaps** [comment]
The issue has been fixed. Please download the latest QM release again.
Thank you for reporting,
--MMS
