### ISSUE TITLE
QM 4.1.2 for Mac: console mode unavailable

### ISSUE THREAD

**Issue by bikeNomad** [QuantumLeaps/qm#2]
I'm trying to write a cross-platform Makefile for a project that includes qm code generation. 

I see that the `qmc` command-line compilation utility no longer exists, and the help documentation says to run `qm` with the `-c` command line argument. However, 
```
/Applications/qm.app/Contents/MacOS/qm -c
```
only succeeds in launching the GUI with a blank window (in which the Command-W close-window keystroke shortcut is not enabled).

How do I run the equivalent of `qmc` on the Mac?

**Comment by bikeNomad** [comment]
copied to the SF tracker

**Comment by quantum-leaps** [comment]
This issue report was copied from SourceForge [bug#205](https://sourceforge.net/p/qpc/bugs/205/). This bug report turns out to be a mistake to use an older version of QM, instead of QM 4.1.2. The command-line code generation works correctly in QM 4.1.2, so this bug report is closed.
--MMS
