### ISSUE TITLE
about QHSM_MAX_NEST_DEPTH_ 

### ISSUE THREAD

**Issue by su782710477** [QuantumLeaps/qm#20]
in the file qep_hsm.c, if the QHSM_MAX_NEST_DEPTH_ value is small than the required  depth, the program maybe  occur erro. and the assert is not effected

**Comment by quantum-leaps** [comment]
Thanks a lot for reporting. Could you perhaps provide an example that would exceed the QHSM_MAX_NEST_DEPTH_ limit, but will not cause assertion failure? This would be very helpful.
--MMS
