### ISSUE TITLE
Assets for old releases are missing

### ISSUE THREAD

**Issue by rnestler** [QuantumLeaps/qm#4]
Releases for old versions (https://github.com/QuantumLeaps/qm/releases/tag/v4.5.1 for example) don't have any assets. Only the latest https://github.com/QuantumLeaps/qm/releases/tag/v5.0.1 has them. Is this intended?

**Comment by quantum-leaps** [comment]
The older QM releases are still available on [SourceForge](https://sourceforge.net/projects/qpc/files/QM/).
As the migration from SourceForge to GitHub progresses, the older releases in all QuantumLeaps repos will be simply preserved.
--MMS
